kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
volumeMounts:
  - mountPath: /var/lib/mysql
    name: mysql-storage