apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/medaminemachfar/cloud-project.git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: cloud project\books-storage-main\Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: my-app:latest
