apiVersion: v1
kind: Template
metadata:
  name: mern-stack-template
  annotations:
    description: "Template to deploy a MERN stack application with a frontend and backend."
objects:
  # Backend Deployment
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: backend
    spec:
      replicas: 1
      selector:
        app: backend
      template:
        metadata:
          labels:
            app: backend
        spec:
          containers:
            - name: backend
              image: "${BACKEND_IMAGE}" # Parameterized image URL
              ports:
                - containerPort: 5000
                  protocol: TCP
              env:
                - name: MONGO_URI
                  value: "${MONGO_URI}" # MongoDB Atlas URI from parameter
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - backend
            from:
              kind: ImageStreamTag
              name: backend-image:latest

  # Backend Service
  - apiVersion: v1
    kind: Service
    metadata:
      name: backend
    spec:
      selector:
        app: backend
      ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000

  # Frontend Deployment
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: frontend
    spec:
      replicas: 1
      selector:
        app: frontend
      template:
        metadata:
          labels:
            app: frontend
        spec:
          containers:
            - name: frontend
              image: "${FRONTEND_IMAGE}" # Parameterized image URL
              ports:
                - containerPort: 80
                  protocol: TCP
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - frontend
            from:
              kind: ImageStreamTag
              name: frontend-image:latest

  # Frontend Service
  - apiVersion: v1
    kind: Service
    metadata:
      name: frontend
    spec:
      selector:
        app: frontend
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80

  # Frontend Route (External Access)
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: frontend
    spec:
      to:
        kind: Service
        name: frontend
      port:
        targetPort: 80
      tls:
        termination: edge
parameters:
  - name: BACKEND_IMAGE
    description: "Docker image for the backend"
    required: true
  - name: FRONTEND_IMAGE
    description: "Docker image for the frontend"
    required: true
  - name: MONGO_URI
    description: "MongoDB Atlas connection URI"
    required: true
